# Author: cleanet
# cleannet29@gmail.com
# 
# Licensed by GNU GENERAL PUBLIC LICENSE VERSION 3
# This file is part of backupSystem.
# backupSystem is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# backupSystem is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with backupSystem. If not, see <https://www.gnu.org/licenses/>.
# Copyright 2023 cleanet
#
# This script file is used for install the service client in Windows
# 
backup:
  source: backup
  destination: backups
data:
  copy:
    # backupSystem
    - source: /etc/backupSystem/start.sh

    - source: /etc/backupSystem/config.yaml

   # FTP
    - source: /tmp/vsftpd.conf
    - source: /tmp/users_vsftpd.deny

    # HTTP
    - source: /tmp/apache2

    # nextcloud
    - source: /nextcloud
    - source: /home/nextcloud
      destination: nextcloud_data

    # DNS
    - source: /tmp/bind

    - source: /tmp/fstab

    - source: /tmp/crontab

    # OTP
    - source: /tmp/security/access-oath.conf
    - source: /tmp/users.oath
    - source: /tmp/pam.d/sshd
    - source: /home/recovery_codes_OTP

    # groups and users
    - source: /tmp/group
    - source: /tmp/passwd
    - source: /tmp/shadow

    # Transmission
    - source: /home/transmission
    - source: /tmp/transmission-daemon

    - source: /tmp/ssh

    # let's encrypt
    - source: /tmp/letsencrypt

    # ansible
    - source: /tmp/ansible
